package me.pajic.tiered_chests.mixin.client;

import me.pajic.tiered_chests.platform.fabric.FabricClientEntrypoint;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.particle.SingleQuadParticle;
import net.minecraft.client.particle.TerrainParticle;
import net.minecraft.client.renderer.texture.TextureAtlas;
import net.minecraft.client.renderer.texture.TextureAtlasSprite;
import net.minecraft.core.BlockPos;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.state.BlockState;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(TerrainParticle.class)
public abstract class TerrainParticleMixin extends SingleQuadParticle {

    protected TerrainParticleMixin(ClientLevel level, double x, double y, double z, TextureAtlasSprite sprite) {
        super(level, x, y, z, sprite);
    }

    @Inject(method = "<init>(Lnet/minecraft/client/multiplayer/ClientLevel;DDDDDDLnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/core/BlockPos;)V", at = @At("RETURN"))
    private void tiered_chests$swapWashedSprite(ClientLevel level, double x, double y, double z, double xa, double ya, double za, BlockState state, BlockPos pos, CallbackInfo ci) {
        if (FabricClientEntrypoint.shouldWash(state.getBlock())) {
            TextureAtlasSprite originalSprite = this.sprite;
            if (originalSprite != null) {
                var atlasManager = ((me.pajic.tiered_chests.mixin.client.MinecraftAccessor) Minecraft.getInstance()).getAtlasManager();
                TextureAtlas atlas = atlasManager.getAtlasOrThrow(Identifier.parse("minecraft:blocks"));
                TextureAtlasSprite washedSprite = atlas.getSprite(originalSprite.contents().name().withSuffix("_washed"));
                
                // Only swap if the washed sprite actually exists (was generated by our other Mixin)
                if (washedSprite != null && !washedSprite.contents().name().getPath().contains("missingno")) {
                    this.sprite = washedSprite;
                }
            }
        }
    }
}
